name: nav_app_ecomputer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  go_router: ^9.0.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  http: ^1.1.0
  firebase_core: ^2.5.0
  cloud_firestore: ^4.8.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  shared_preferences: ^2.2.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
